export const LTX_STORAGE_KEY = "guaardvark.ltx-director.v4";

export const DEFAULT_LTX_CONFIG = {
  performance_profile: "custom",
  mode: "i2v",
  prompt: "",
  negative_prompt: "",
  model_id: "ltx23-dasiwa-dragonleap-v4",
  model_name: "LTX2/DasiwaLTX23_dragonleapV4.safetensors",
  model_format: "safetensors",
  text_encoder: "gemma-3-12b-it-heretic-v2_fp8_e4m3fn.safetensors",
  text_projection: "ltx-2.3_text_projection_bf16.safetensors",
  video_vae: "LTX2/LTX23_video_vae_bf16.safetensors",
  audio_vae: "LTX2/LTX23_audio_vae_bf16.safetensors",
  preview_vae: "LTX2/taeltx2_3.safetensors",
  spatial_upscaler: "ltx-2.3-spatial-upscaler-x2-1.1.safetensors",
  temporal_upscaler: "ltx-2.3-temporal-upscaler-x2-1.0.safetensors",
  source_image: null,
  last_frame: null,
  source_video: null,
  audio_source: "generated",
  uploaded_audio: null,
  width: 576,
  height: 896,
  fps: 24,
  duration_seconds: 8,
  seed: 42,
  resize_method: "maintain aspect ratio",
  guide_strength: 1,
  motion_guide_strength: 1,
  timeline_segments: [],
  motion_segments: [],
  audio_segments: [],
  distilled_lora: false,
  distilled_lora_name: "LTX/ltx-2.3-22b-distilled-lora-1.1_fro90_ceil72_condsafe.safetensors",
  distilled_lora_strength: 0.5,
  bodyphysics_lora: false,
  bodyphysics_lora_name: "LTX/DaSiWa_LTX23_NSFW_Bodyphysics_Fluid_Motion_Enhancer_v01.safetensors",
  bodyphysics_lora_strength: 0.5,
  loras: [],
  sampler: "euler_cfg_pp",
  pass1: { enabled: true, cfg: 1, steps: 10, scheduler: "linear_quadratic", denoise: 1 },
  pass2: { enabled: true, cfg: 1, steps: 4, scheduler: "linear_quadratic", denoise: 0.3 },
  pass3: { enabled: false, cfg: 1, steps: 2, scheduler: "linear_quadratic", denoise: 0.2 },
  chunking: false,
  chunk_count: 2,
  chunk_dim_threshold: 4096,
  vram_headroom: 2,
  fp16_accumulation: false,
  sage_attention: "off",
  sage_kernel: "auto",
  sage_allow_compile: false,
  sage_triton_kernels: true,
  nag: { enabled: false, scale: 11, alpha: 0.25, tau: 2.5, inplace: true },
  tiled_vae: false,
  tiled_spatial_tiles: 4,
  tiled_spatial_overlap: 4,
  tiled_temporal_tile_length: 32,
  tiled_temporal_overlap: 8,
  tiled_last_frame_fix: false,
  tiled_working_device: "auto",
  tiled_working_dtype: "auto",
  tile_size: 512,
  temporal_upscale: false,
  simple_upscale: false,
  simple_upscale_factor: 2,
  model_upscale: false,
  upscale_model: "",
  rtx: { enabled: false, scale: 2, quality: "Ultra" },
  color_transfer: { enabled: false, method: "reinhard_lab", strength: 0.75 },
  watermark: { enabled: false, path: null, position: "top-left", scale: 0.12, opacity: 0.35 },
  soundmark: { enabled: false, path: null },
  output_format: "video/h264-mp4",
  crf: 19,
  pix_fmt: "yuv420p",
  save_metadata: true,
};

export const LTX_MODEL_OPTIONS = {
  "ltx23-dasiwa-dragonleap-v4": {
    label: "DragonLeap V4 safetensors",
    model_name: "LTX2/DasiwaLTX23_dragonleapV4.safetensors",
    model_format: "safetensors",
  },
  "ltx23-dev-gguf-unsloth-q8": {
    label: "LTX 2.3 DEV GGUF Unsloth Q8_0",
    model_name: "LTX2/ltx23DEVGGUFUnsloth_q80.gguf",
    model_format: "gguf",
  },
  "ltx23-fp8-civitai-2752717": {
    label: "LTX 2.3 FP8 (Civitai)",
    model_name: "LTX2/ltx23_fp8.safetensors",
    model_format: "safetensors",
  },
};

export const MODE_HELP = {
  i2v: "Animate one source image.",
  flf2v: "Interpolate between explicit first and last frames.",
  t2v: "Generate from prompt and Director timeline only.",
  v2v: "Transform a source video; source audio can be retained.",
};

export const QUALITY_PRESETS = {
  preview: {
    label: "Preview",
    patch: { width: 512, height: 896, duration_seconds: 4, pass2: { enabled: false }, pass3: { enabled: false }, tiled_vae: true },
  },
  balanced: {
    label: "Balanced",
    patch: { width: 576, height: 896, duration_seconds: 8, pass2: { enabled: true, cfg: 1, steps: 4, scheduler: "linear_quadratic", denoise: 0.3 }, pass3: { enabled: false } },
  },
  final: {
    label: "Final",
    patch: { width: 576, height: 896, duration_seconds: 10, pass2: { enabled: true, cfg: 1, steps: 4, scheduler: "linear_quadratic", denoise: 0.3 }, pass3: { enabled: true, cfg: 1, steps: 2, scheduler: "linear_quadratic", denoise: 0.2 } },
  },
};

// Workflow-level presets intentionally live beside the LTX config, separate
// from the generic preview/balanced/final UI presets above.
export const LTX_WORKFLOW_PRESETS = {
  lightspeed: {
    label: "Lightspeed",
    description: "4-step preview: distilled LoRA, single pass, no upscale.",
    patch: {
      profile_id: "lightspeed",
      performance_profile: "lightspeed",
      width: 576,
      height: 896,
      duration_seconds: 4,
      fps: 24,
      vram_headroom: 3,
      distilled_lora: true,
      distilled_lora_strength: 0.5,
      bodyphysics_lora: false,
      loras: [],
      pass1: { enabled: true, cfg: 1, steps: 4, scheduler: "linear_quadratic", denoise: 1 },
      pass2: { enabled: false },
      pass3: { enabled: false },
      chunking: true,
      chunk_count: 2,
      chunk_dim_threshold: 4096,
      tiled_vae: true,
      tiled_spatial_tiles: 4,
      tiled_spatial_overlap: 4,
      tiled_temporal_tile_length: 32,
      tiled_temporal_overlap: 8,
      tiled_working_device: "auto",
      tiled_working_dtype: "auto",
      sage_attention: "off",
      sage_triton_kernels: false,
      nag: { enabled: false, scale: 11, alpha: 0.25, tau: 2.5, inplace: true },
      temporal_upscale: false,
      simple_upscale: false,
      model_upscale: false,
      rtx: { enabled: false },
      color_transfer: { enabled: false },
      watermark: { enabled: false },
      soundmark: { enabled: false },
    },
  },
  quality: {
    label: "Quality",
    description: "Full-model quality path: no distilled LoRA, two-pass sampling.",
    patch: {
      profile_id: "quality",
      performance_profile: "quality",
      width: 576,
      height: 896,
      fps: 24,
      duration_seconds: 8,
      vram_headroom: 3,
      distilled_lora: false,
      bodyphysics_lora: false,
      pass1: { enabled: true, cfg: 1, steps: 10, scheduler: "linear_quadratic", denoise: 1 },
      pass2: { enabled: true, cfg: 1, steps: 4, scheduler: "linear_quadratic", denoise: 0.3 },
      pass3: { enabled: false },
      chunking: true,
      chunk_count: 2,
      chunk_dim_threshold: 4096,
      tiled_vae: true,
      tiled_spatial_tiles: 4,
      tiled_spatial_overlap: 4,
      tiled_temporal_tile_length: 32,
      tiled_temporal_overlap: 8,
      tiled_working_device: "auto",
      tiled_working_dtype: "auto",
      sage_attention: "off",
      sage_triton_kernels: false,
      nag: { enabled: false, scale: 11, alpha: 0.25, tau: 2.5, inplace: true },
      temporal_upscale: false,
      simple_upscale: false,
      model_upscale: false,
      rtx: { enabled: false },
      color_transfer: { enabled: false },
      watermark: { enabled: false },
      soundmark: { enabled: false },
    },
  },
};

export const mergeLtxConfig = (base, patch) => {
  const result = { ...base, ...patch };
  ["pass1", "pass2", "pass3", "nag", "rtx", "color_transfer", "watermark", "soundmark"].forEach((key) => {
    if (patch[key]) result[key] = { ...(base[key] || {}), ...patch[key] };
  });
  return result;
};
